# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://localhost:8080/events/target
Content-Type: application/json

{
  "shoesList":
  [
    {"brand":"나이키","name":"코르테즈","size":265},
    {"brand":"아디다스","name":"슈퍼스타","size":260}
  ],
  "target":
  {"brand":"컨버스","name":"척테일러"}
}
###
POST http://localhost:8080/events/target
Content-Type: application/json

{
"shoesList":
[
{"brand":"나이키","name":"코르테즈","size":265},
{"brand":"컨버스","name":"척테일러","size":260}
],
"target":
{"brand":"아디다스","name":"슈퍼스타"}
}

###
POST http://localhost:8080/events/target
Content-Type: application/json

{
  "shoesList":
  [
    {"brand":"나이키","name":"코르테즈","size":265},
    {"brand":"나이키","name":"코르테즈","size":260}
  ],
  "target":
  {"brand":"아디다스","name":"슈퍼스타"}
}


###
POST http://localhost:8080/events/list
Content-Type: application/json

{
}
###