
spring:
  profiles:
    active: local

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

# 운영 환경
---
spring.profiles: set1
spring.profiles.include: real-db

server:
  port: 8081

---
spring.profiles: set2
spring.profiles.include: real-db

server:
  port: 8082
# 로컬 환경
---

spring:
  profiles: local
  datasource:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true