
spring:
  profiles:
    active: local

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

# 운영 환경
---
spring.profiles: set1
spring.profiles.include: real-db

server:
  port: 8081

---
spring.profiles: set2
spring.profiles.include: real-db

server:
  port: 8082
# 로컬 환경
---

spring:
  profiles: local
  datasource:
    platform: h2
    url: jdbc:h2:~/test;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      show-sql: true
      hibernate:
        ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
